package com.projctrfade.safdjw.ui.dayview;

public enum LIST_ITEM_TYPE {
    FULL_HOUR,
    HALF_HALF,
    QUARTER_QUARTER_HALF,
    QUARTER_HALF_QUARTER,
    HALF_QUARTER_QUARTER,
    QUARTER_THREE_QUARTER,
    THREE_QUARTER_QUARTER,
    QUARTER_QUARTER_QUARTER_QUARTER

}
